defaultPortal: TPP
portals:
  - name: TPP
    portalId: 2359872
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPG-2eK8LhIEAA0ADBjAhJABIOL-twEo7ukMMhkAlQcVpjG1XV5-naDW80a4JdGug5uxM_v7OhgAAARBAAAAeAAAAAAAAAAAgAEAAAAAAARCGQCVBxWmGqHm1XwonmVLJ16AXBNdjfAJYfc
        expiresAt: '2020-08-08T04:31:19.414Z'
    personalAccessKey: >-
      CiQ5ZjJhMWQzMC0yYTFhLTRkMTAtOWU5Ny03M2FkYjhiNWQyYzgQwISQARji_rcBKhkABeaRgmzN3a2tWLvVvQ6_lsRYxlYKxAgd
